"""SQLite-Persistenz des Kanban-Moduls - Fassade.

Dies ist nur noch die Fassade: Die Implementierung liegt in den thematischen
Modulen persistence_basis (Querschnitts-Helfer), persistence_schema (Schema,
Migration, Seed), persistence_struktur (Mappen, Boards, Spalten),
persistence_karten (Karten, Timer, Zeiteinträge) und persistence_inhalte
(Dokumente, Labels, Anhänge, Aktivität, Export). Hier werden alle bisherigen
Namen re-exportiert - öffentliche wie modulinterne -, damit kein Aufrufer
angepasst werden muss.
"""
from __future__ import annotations

from app.db import DB_PFAD, verbindung

from .models import (
    Aktivitaet,
    Anhang,
    Board,
    BoardDetail,
    Dokument,
    DokumentUpdate,
    FaelligEintrag,
    GruppenMitglied,
    HeuteUebersicht,
    Karte,
    KarteUpdate,
    LabelDefinition,
    LabelUpdate,
    MappeUpdate,
    ProjektAufwand,
    ProjektBoardAufwand,
    ProjektDetail,
    ProjektPersonAufwand,
    Projektmappe,
    Spalte,
    SpalteUpdate,
    Zeiteintrag,
    ZeiteintragUpdate,
)
from .persistence_basis import (
    _als_int,
    _jetzt,
    _jetzt_genau,
    _protokolliere,
    _protokolliere_feldaenderungen,
    _tagessegmente,
    _verb,
)
from .persistence_inhalte import (
    ANHANG_MAX_BYTES,
    LabelNameBelegt,
    _anhang_aus_row,
    _benenne_label_in_karten,
    _dokument_aus_row,
    _export_board_kern,
    _export_karten,
    _loesche_anhang_dateien,
    aktivitaet_fuer,
    aktualisiere_dokument,
    aktualisiere_label,
    anhaenge_dir,
    anhang_pfad,
    erstelle_dokument,
    erstelle_label,
    export_board,
    export_mappe,
    faellige_karten,
    hole_anhang,
    hole_dokument,
    hole_kanban_einstellungen,
    hole_label,
    karten_aktivitaet,
    liste_anhaenge,
    liste_dokumente,
    liste_labels,
    loesche_anhang,
    loesche_dokument,
    loesche_label,
    setze_kanban_einstellungen,
    speichere_anhang,
    was_steht_an,
)
from .persistence_karten import (
    _ABSCHLUSS_SQL,
    _VOLLTEXT_SQL,
    _ZE_SELECT,
    _archiv_grenze,
    _karte_aus_row,
    _karte_mit_abschluss,
    _kompaktiere,
    _loesche_marken,
    _loesche_serien_fuer_boards,
    _mappe_fuer_board,
    _naechste_reihenfolge,
    _pause_intern,
    _raeume_karten_restdaten,
    _recompute_erfasst,
    _reichere_gruppen_an,
    _suchbedingung,
    _zeiteintrag_aus_row,
    _zeitfenster,
    aktualisiere_karte,
    aktualisiere_zeiteintrag,
    archiv_seite,
    erstelle_karte,
    erstelle_zeiteintrag,
    fertige_seite,
    finde_karte_per_text,
    hole_karte,
    hole_zeiteintrag,
    checkliste_punkt_aendern,
    checkliste_punkt_anhaengen,
    checkliste_punkt_loeschen,
    kommentar_anhaengen,
    laufende_karte,
    letztes_serie_datum,
    loesche_karte,
    loesche_zeiteintrag,
    loese_verknuepfung,
    markiere_serie,
    serien_instanz_existiert,
    setze_gruppe_zeit_geteilt,
    setze_ticketzeit,
    timer_pause,
    timer_start,
    verknuepfe_karten,
    verschiebe_karte,
    zeiteintraege_range,
)
from .persistence_schema import (
    SCHEMA,
    _konsolidiere_auto_zeiten,
    _migriere,
    _seed,
    init_db,
)
from .persistence_struktur import (
    _kompaktiere_spalten,
    _kuerzel,
    _sichtbarkeits_klausel,
    _spalten,
    aktualisiere_board,
    aktualisiere_mappe,
    aktualisiere_spalte,
    board_detail,
    board_mappe_id,
    done_spalte_id,
    entferne_mappe_mitglied,
    erstelle_board,
    erstelle_mappe,
    erstelle_spalte,
    gruppe_mappe_id,
    hole_spalte,
    karte_mappe_id,
    liste_boards,
    liste_mappen,
    loesche_board,
    loesche_mappe,
    loesche_spalte,
    mappe_mitglieder,
    mappe_sichtbar_fuer,
    projekt_aufwand_liste,
    projekt_detail,
    setze_erledigt_spalte,
    setze_mappe_mitglied,
    setze_spalten_reihenfolge,
    sichtbare_mappen_ids,
    spalte_mappe_id,
    verschiebe_spalte,
    zaehle_mappen,
)
